version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
  - source: style.css
    destination: /var/www/html
  - source: script.js
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: /opt/codedeploy-agent/deployment-root/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /opt/codedeploy-agent/deployment-root/scripts/configure_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/scripts/start_server.sh
      timeout: 300
      runas: root
